// Which backend the UI talks to.
//
// LOCAL DEV: leave this empty. The app falls back to the page's own origin,
// which is what you want when the same FastAPI server serves the UI.
//
// VERCEL: do not edit this file. The build step (inject-config.js) overwrites it
// from the AGENT2AGENT_API environment variable set in the Vercel dashboard.
// It can also be overridden per visit with ?api=<url> for testing a staging
// backend without touching any config.
window.AGENT2AGENT_API = "";