// Vercel build step: writes config.js from the AGENT2AGENT_API env var.
//
//   Vercel Build Command:  node inject-config.js
//   Vercel Env Variable:   AGENT2AGENT_API = https://agent2agent-api.onrender.com
//
// No dependencies, runs on the Node that ships with Vercel. Locally this file is
// never run, so the committed config.js keeps its empty same-origin default and
// the UI talks to a locally running API.

const fs = require("fs");
const path = require("path");

const api = (process.env.AGENT2AGENT_API || "").trim();
const target = path.join(__dirname, "config.js");

const contents = [
  "// Generated by inject-config.js at build time. Do not edit by hand.",
  "// Set AGENT2AGENT_API in the Vercel dashboard to point the UI at a backend.",
  `window.AGENT2AGENT_API = ${JSON.stringify(api)};`,
  "",
].join("\n");

fs.writeFileSync(target, contents, "utf8");

console.log(
  api
    ? `inject-config: AGENT2AGENT_API set to ${api}`
    : "inject-config: AGENT2AGENT_API not set, UI will call its own origin"
);